variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:latest


stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: "overlay"
  before_script:
    - "docker ps"
    - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  script:
    - docker build --rm -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE
  only:
    refs:
      - master


deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - 'which ssh-agent || ( apk update && apk add openssh)'
    - mkdir -p ~/.ssh
    - echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts
    - scp -o "StrictHostKeyChecking no" -r docker-compose-prod.yml $SERVER_USER@$SERVER_HOST:/home/docker-ci/iwex/docker-compose.yml
    - ssh -o "StrictHostKeyChecking no" $SERVER_USER@$SERVER_HOST "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY; cd /home/docker-ci/iwex; docker-compose pull; docker-compose up -d; docker system prune -f"
  only:
    refs:
      - master
