version: '3'
services:
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # nginx:
  #   image: nginx:1.15
  #   restart: always
  #   volumes:
  #     - ./etc/nginx.conf:/etc/nginx/nginx.conf
  #     - ./etc/ssl/:/etc/nginx/ssl/
  #     - medias:/media
  #     - statics:/static
  #     - common_files:/common_files
  #   ports:
  #     - 443:443
  #     - 80:80

  app:
    build: . 
    restart: always
    command: >
          bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py makemessages -l de && python manage.py compilemessages && python  manage.py runserver 0.0.0.0:8005"
    ports:
          - "8005:8005"
    env_file:
      - .env
    depends_on:
      - db 
    volumes:
      - /home/iwex-crm-master/media:/app/media


volumes:
  pgdata:
  medias:

