# Generated by Django 3.2 on 2023-09-20 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_supportrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('support_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='accounts.supportrequest')),
            ],
        ),
    ]
