# Generated by Django 3.2 on 2023-09-20 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_supportresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportresponse',
            name='support_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='accounts.supportrequest'),
        ),
    ]
