# Generated by Django 3.2 on 2023-09-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_payment_remaining_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileInPayment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_choice',
            field=models.DecimalField(choices=[(10000, 'Десять тысяч'), (20000, 'Двадцать тысяч'), (35000, 'Тридцать пять тысяч')], decimal_places=2, default=0, max_digits=10, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Остаток'),
        ),
    ]
