# Generated by Django 3.2 on 2023-09-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20230925_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_choice',
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплачено'),
        ),
    ]
