# Generated by Django 3.2 on 2023-09-25 09:22

import applications.accounts.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20230925_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(default=applications.accounts.models.get_due_date, verbose_name='Крайний срок оплаты'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2023, 9, 25), verbose_name='Дата оплаты'),
            preserve_default=False,
        ),
    ]
