# Generated by Django 3.2 on 2023-09-25 09:26

import applications.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20230925_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(default=applications.accounts.models.get_due_date, null=True, verbose_name='Крайний срок оплаты'),
        ),
    ]
