# Generated by Django 3.2 on 2023-09-26 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_payment_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportrequest',
            options={'verbose_name': 'Тех поддержка', 'verbose_name_plural': 'Тех поддержка'},
        ),
        migrations.AddField(
            model_name='supportresponse',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
