# Generated by Django 3.2 on 2023-09-26 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='student_documents/', verbose_name='Документ')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('jpg', 'JPG'), ('png', 'PNG')], max_length=5, verbose_name='Формат документа')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_documents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Документ Студента',
                'verbose_name_plural': 'Документы Студентов',
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
