<<<<<<< HEAD
# Generated by Django 3.2 on 2023-11-13 08:02
=======
# Generated by Django 3.2 on 2023-12-25 07:51
>>>>>>> origin/master

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20231113_1141'),
        ('accounts', '0020_auto_20231113_1331'),
    ]

    operations = [
    ]
