# Generated by Django 3.2 on 2023-09-27 05:11

import applications.accounts.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20230926_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={},
        ),
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateField(default=applications.accounts.models.get_due_date, null=True, verbose_name='Крайний срок оплаты'),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_fully_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено полностью'),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания платежа'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='pay_sum',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма оплаты'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения платежа'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
