# Generated by Django 3.2 on 2023-11-28 07:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='manager_notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Примечание менеджера'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='arrival_place',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Пункт назначения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='characteristics',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='courses_info',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='living_condition',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Условия проживания'),
        ),
        migrations.AlterField(
            model_name='profilehistory',
            name='changes',
            field=ckeditor.fields.RichTextField(verbose_name='Текст изменения'),
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='message',
            field=ckeditor.fields.RichTextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='supportresponse',
            name='message',
            field=ckeditor.fields.RichTextField(verbose_name='Ответ'),
        ),
    ]
