# Generated by Django 3.2 on 2024-01-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20231225_1351'),
        ('accounts', '0023_auto_20231128_1313'),
    ]

    operations = [
    ]
