# Generated by Django 3.2 on 2024-01-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_merge_0022_auto_20231225_1351_0023_auto_20231128_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название карточки')),
                ('content_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на содержимое')),
                ('content_file', models.FileField(blank=True, null=True, upload_to='card_files/', verbose_name='Файл содержимого')),
            ],
        ),
    ]
