# Generated by Django 3.2 on 2023-09-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_payment_who_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileInRegistration',
        ),
    ]
