# Generated by Django 3.2 on 2023-10-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_delete_profileinregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chinese',
            field=models.CharField(blank=True, choices=[('C2', 'В совершенстве'), ('C1', 'Очень хорошо'), ('B2', 'Хорошо'), ('B1', 'Разговорный'), ('A2', 'Обучаюсь'), ('A1', 'Начальный'), ('0', 'Не знаю')], default='', max_length=10, verbose_name='Знание китайского языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='english',
            field=models.CharField(blank=True, choices=[('C2', 'В совершенстве'), ('C1', 'Очень хорошо'), ('B2', 'Хорошо'), ('B1', 'Разговорный'), ('A2', 'Обучаюсь'), ('A1', 'Начальный'), ('0', 'Не знаю')], default='', max_length=10, verbose_name='Знание английского языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default='', max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='german',
            field=models.CharField(blank=True, choices=[('C2', 'В совершенстве'), ('C1', 'Очень хорошо'), ('B2', 'Хорошо'), ('B1', 'Разговорный'), ('A2', 'Обучаюсь'), ('A1', 'Начальный'), ('0', 'Не знаю')], default='', max_length=10, verbose_name='Знание немецкого языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='russian',
            field=models.CharField(blank=True, choices=[('C2', 'В совершенстве'), ('C1', 'Очень хорошо'), ('B2', 'Хорошо'), ('B1', 'Разговорный'), ('A2', 'Обучаюсь'), ('A1', 'Начальный'), ('0', 'Не знаю')], default='', max_length=10, verbose_name='Знание русского языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='turkish',
            field=models.CharField(blank=True, choices=[('C2', 'В совершенстве'), ('C1', 'Очень хорошо'), ('B2', 'Хорошо'), ('B1', 'Разговорный'), ('A2', 'Обучаюсь'), ('A1', 'Начальный'), ('0', 'Не знаю')], default='', max_length=10, verbose_name='Знание турецкого языка'),
        ),
    ]
