# Generated by Django 3.2 on 2023-10-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_announcement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='send_to_employers',
            field=models.BooleanField(default=False, verbose_name='Отправить работодателям'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='send_to_students',
            field=models.BooleanField(default=False, verbose_name='Отправить студентам'),
        ),
    ]
