# Generated by Django 3.2 on 2023-10-12 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_user_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Емайл')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('manager_notes', models.TextField(blank=True, null=True, verbose_name='Примечание менеджера')),
                ('call_date', models.DateField(blank=True, null=True, verbose_name='Дата звонка')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
