# Generated by Django 3.2 on 2023-10-12 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_connectionrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionrequest',
            options={'verbose_name': 'Заявка на подключение', 'verbose_name_plural': 'Заявки на подключение'},
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
