# Generated by Django 3.2 on 2023-10-12 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20231012_0434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionrequest',
            name='full_name',
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Емайл'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
