# Generated by Django 3.2 on 2023-10-12 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20231012_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='call_later',
            field=models.BooleanField(default=False, verbose_name='Набрать позже'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='called',
            field=models.BooleanField(default=False, verbose_name='Позвонил'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='consulted',
            field=models.BooleanField(default=False, verbose_name='Проконсультирован'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата заявки'),
        ),
        migrations.AlterField(
            model_name='connectionrequest',
            name='call_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата звонка менеджера'),
        ),
    ]
