# Generated by Django 3.2 on 2023-10-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20231012_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
    ]
