# Generated by Django 3.2 on 2023-11-28 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_user_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ProfileInArchive',
        ),
        migrations.DeleteModel(
            name='ProfileInRefused',
        ),
        migrations.DeleteModel(
            name='ProfileInSending',
        ),
        migrations.DeleteModel(
            name='ProfileInTermin',
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
            ],
            options={
                'verbose_name': 'Контакт студента',
                'verbose_name_plural': 'Контакты студентов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.profile',),
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['last_name', 'first_name', '-creation_date'], 'verbose_name': 'Профиль студента', 'verbose_name_plural': 'Профили студентов'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='connectionrequest',
            name='processed',
        ),
        migrations.AddField(
            model_name='announcement',
            name='specific_employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employer_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='specific_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='announcement_videos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_country',
            field=models.CharField(blank=True, choices=[('Кыргызстан', 'Кыргызстан'), ('Казахстан', 'Казахстан'), ('Узбекистан', 'Узбекистан'), ('Таджикистан', 'Таджикистан'), ('Россия', 'Россия'), ('Türkei', 'Турция')], default='', max_length=50, verbose_name='Страна рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='chinese',
            field=models.CharField(blank=True, choices=[('C2', 'В совершенстве'), ('C1', 'Очень хорошо'), ('B2', 'Хорошо'), ('B1', 'Разговорный'), ('A2', 'Обучаюсь'), ('A1', 'Начальный'), ('0', 'Не знаю')], default='', max_length=150, verbose_name='Знание китайского языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country1',
            field=models.CharField(blank=True, choices=[('Кыргызстан', 'Кыргызстан'), ('Россия', 'Россия'), ('Турция', 'Турция'), ('Казахстан', 'Казахстан'), ('Германия', 'Германия'), ('Узбекистан', 'Узбекистан'), ('Таджикистан', 'Таджикистан'), ('Дубай', 'Дубай'), ('USA', 'Америка'), ('другое', 'другое')], default='', max_length=50, verbose_name='Страна (1 место работы)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country2',
            field=models.CharField(blank=True, choices=[('Кыргызстан', 'Кыргызстан'), ('Россия', 'Россия'), ('Турция', 'Турция'), ('Казахстан', 'Казахстан'), ('Германия', 'Германия'), ('Узбекистан', 'Узбекистан'), ('Таджикистан', 'Таджикистан'), ('Дубай', 'Дубай'), ('USA', 'Америка'), ('другое', 'другое')], default='', max_length=50, verbose_name='Страна (2 место работы)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country3',
            field=models.CharField(blank=True, choices=[('Кыргызстан', 'Кыргызстан'), ('Россия', 'Россия'), ('Турция', 'Турция'), ('Казахстан', 'Казахстан'), ('Германия', 'Германия'), ('Узбекистан', 'Узбекистан'), ('Таджикистан', 'Таджикистан'), ('Дубай', 'Дубай'), ('USA', 'Америка'), ('другое', 'другое')], default='', max_length=50, verbose_name='Страна (3 место работы)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='english',
            field=models.CharField(blank=True, choices=[('C2', 'В совершенстве'), ('C1', 'Очень хорошо'), ('B2', 'Хорошо'), ('B1', 'Разговорный'), ('A2', 'Обучаюсь'), ('A1', 'Начальный'), ('0', 'Не знаю')], default='', max_length=150, verbose_name='Знание английского языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], default='', max_length=20, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='german',
            field=models.CharField(blank=True, choices=[('C2', 'В совершенстве'), ('C1', 'Очень хорошо'), ('B2', 'Хорошо'), ('B1', 'Разговорный'), ('A2', 'Обучаюсь'), ('A1', 'Начальный'), ('0', 'Не знаю')], default='', max_length=150, verbose_name='Знание немецкого языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(blank=True, choices=[('a0', 'A0'), ('a1', 'A1'), ('a1+', 'A1+'), ('a2', 'A2'), ('a2+', 'A2+'), ('b1', 'B1'), ('b1+', 'B1+'), ('b2', 'B2'), ('b2+', 'B2+'), ('c1', 'C1')], default='', max_length=20, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Кыргызстан', 'Кыргызстан'), ('Казахстан', 'Казахстан'), ('Узбекистан', 'Узбекистан'), ('Таджикистан', 'Таджикистан'), ('Россия', 'Россия'), ('другое', 'другое')], default='', max_length=50, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position1',
            field=models.CharField(blank=True, choices=[('Kellner', 'Официант'), ('Verkäufer', 'Продавец'), ('Kassierer', 'Кассир'), ('Küchenhelfer', 'Кух. работник'), ('Zimmermädchen', 'Горничная'), ('Rezeptionist', 'Ресепшн'), ('Lager', 'Грузчик'), ('Taxifahrer', 'Таксист'), ('Lehrer', 'Преподаватель'), ('Kinderfrau', 'Няня'), ('Bote', 'Курьер'), ('Sekretär', 'Секретарь'), ('Feldarbeiter', 'Работа на полях'), ('Call-Center-Betreiber', 'Оператор call-центра'), ('Wächter', 'Охранник'), ('Promoter', 'Промоутер'), ('Barmann', 'Бармен'), ('Reiseführer', 'Гид'), ('Animateur', 'Аниматор'), ('Tankwagen', 'Заправщик'), ('Verwalter', 'Администратор'), ('Packer', 'Упаковщик'), ('Nähwerkarbeiter', 'Работа в швейном цеху'), ('Putzfrau', 'Уборщица'), ('Hirt', 'Пастух'), ('Bauernarbeiter', 'Работа на фермах'), ('Sanitäter', 'Санитар'), ('Bauarbeiter', 'Строитель'), ('Visagist', 'Визажист'), ('Designer', 'Дизайнер'), ('Haushälterin', 'Домохозяйка'), ('Lagerverwalter', 'Кладовщик'), ('Absatzforscher', 'Маркетолог'), ('Masseur', 'Массажист'), ('Möbelbauer', 'Мебельщик'), ('Krankenpfleger', 'Медбрат'), ('Krankenschwester', 'Медсестра'), ('Manager', 'Мэнеджер'), ('Monteur', 'Монтёр'), ('Operator', 'Оператор'), ('Finisher', 'Отделочник'), ('Friseur', 'Парикмахер'), ('Übersetzer', 'Переводчик'), ('Koch', 'Повар'), ('Geschirrspüler', 'Посудомойщик'), ('Briefträger', 'Почтальон'), ('Wäscherin', 'Прачка'), ('Lagerarbeiter', 'Работа на складах'), ('Hilfsarbeiter', 'Разнорабочий'), ('Installateur', 'Сантехник'), ('Schweißer', 'Сварщик'), ('Krankenpflegerin', 'Сиделка'), ('Handelsvertreter', 'Торговый агент'), ('Trainer', 'Тренер'), ('Raumpfleger', 'Уборщик'), ('Fotograf', 'Фотограф'), ('Choreograph', 'Хореограф'), ('Elektriker', 'Хореограф')], default='', max_length=50, verbose_name='Должность (1 место работы)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position2',
            field=models.CharField(blank=True, choices=[('Kellner', 'Официант'), ('Verkäufer', 'Продавец'), ('Kassierer', 'Кассир'), ('Küchenhelfer', 'Кух. работник'), ('Zimmermädchen', 'Горничная'), ('Rezeptionist', 'Ресепшн'), ('Lager', 'Грузчик'), ('Taxifahrer', 'Таксист'), ('Lehrer', 'Преподаватель'), ('Kinderfrau', 'Няня'), ('Bote', 'Курьер'), ('Sekretär', 'Секретарь'), ('Feldarbeiter', 'Работа на полях'), ('Call-Center-Betreiber', 'Оператор call-центра'), ('Wächter', 'Охранник'), ('Promoter', 'Промоутер'), ('Barmann', 'Бармен'), ('Reiseführer', 'Гид'), ('Animateur', 'Аниматор'), ('Tankwagen', 'Заправщик'), ('Verwalter', 'Администратор'), ('Packer', 'Упаковщик'), ('Nähwerkarbeiter', 'Работа в швейном цеху'), ('Putzfrau', 'Уборщица'), ('Hirt', 'Пастух'), ('Bauernarbeiter', 'Работа на фермах'), ('Sanitäter', 'Санитар'), ('Bauarbeiter', 'Строитель'), ('Visagist', 'Визажист'), ('Designer', 'Дизайнер'), ('Haushälterin', 'Домохозяйка'), ('Lagerverwalter', 'Кладовщик'), ('Absatzforscher', 'Маркетолог'), ('Masseur', 'Массажист'), ('Möbelbauer', 'Мебельщик'), ('Krankenpfleger', 'Медбрат'), ('Krankenschwester', 'Медсестра'), ('Manager', 'Мэнеджер'), ('Monteur', 'Монтёр'), ('Operator', 'Оператор'), ('Finisher', 'Отделочник'), ('Friseur', 'Парикмахер'), ('Übersetzer', 'Переводчик'), ('Koch', 'Повар'), ('Geschirrspüler', 'Посудомойщик'), ('Briefträger', 'Почтальон'), ('Wäscherin', 'Прачка'), ('Lagerarbeiter', 'Работа на складах'), ('Hilfsarbeiter', 'Разнорабочий'), ('Installateur', 'Сантехник'), ('Schweißer', 'Сварщик'), ('Krankenpflegerin', 'Сиделка'), ('Handelsvertreter', 'Торговый агент'), ('Trainer', 'Тренер'), ('Raumpfleger', 'Уборщик'), ('Fotograf', 'Фотограф'), ('Choreograph', 'Хореограф'), ('Elektriker', 'Хореограф')], default='', max_length=50, verbose_name='Должность (2 место работы)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position3',
            field=models.CharField(blank=True, choices=[('Kellner', 'Официант'), ('Verkäufer', 'Продавец'), ('Kassierer', 'Кассир'), ('Küchenhelfer', 'Кух. работник'), ('Zimmermädchen', 'Горничная'), ('Rezeptionist', 'Ресепшн'), ('Lager', 'Грузчик'), ('Taxifahrer', 'Таксист'), ('Lehrer', 'Преподаватель'), ('Kinderfrau', 'Няня'), ('Bote', 'Курьер'), ('Sekretär', 'Секретарь'), ('Feldarbeiter', 'Работа на полях'), ('Call-Center-Betreiber', 'Оператор call-центра'), ('Wächter', 'Охранник'), ('Promoter', 'Промоутер'), ('Barmann', 'Бармен'), ('Reiseführer', 'Гид'), ('Animateur', 'Аниматор'), ('Tankwagen', 'Заправщик'), ('Verwalter', 'Администратор'), ('Packer', 'Упаковщик'), ('Nähwerkarbeiter', 'Работа в швейном цеху'), ('Putzfrau', 'Уборщица'), ('Hirt', 'Пастух'), ('Bauernarbeiter', 'Работа на фермах'), ('Sanitäter', 'Санитар'), ('Bauarbeiter', 'Строитель'), ('Visagist', 'Визажист'), ('Designer', 'Дизайнер'), ('Haushälterin', 'Домохозяйка'), ('Lagerverwalter', 'Кладовщик'), ('Absatzforscher', 'Маркетолог'), ('Masseur', 'Массажист'), ('Möbelbauer', 'Мебельщик'), ('Krankenpfleger', 'Медбрат'), ('Krankenschwester', 'Медсестра'), ('Manager', 'Мэнеджер'), ('Monteur', 'Монтёр'), ('Operator', 'Оператор'), ('Finisher', 'Отделочник'), ('Friseur', 'Парикмахер'), ('Übersetzer', 'Переводчик'), ('Koch', 'Повар'), ('Geschirrspüler', 'Посудомойщик'), ('Briefträger', 'Почтальон'), ('Wäscherin', 'Прачка'), ('Lagerarbeiter', 'Работа на складах'), ('Hilfsarbeiter', 'Разнорабочий'), ('Installateur', 'Сантехник'), ('Schweißer', 'Сварщик'), ('Krankenpflegerin', 'Сиделка'), ('Handelsvertreter', 'Торговый агент'), ('Trainer', 'Тренер'), ('Raumpfleger', 'Уборщик'), ('Fotograf', 'Фотограф'), ('Choreograph', 'Хореограф'), ('Elektriker', 'Хореограф')], default='', max_length=50, verbose_name='Должность (3 место работы)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='russian',
            field=models.CharField(blank=True, choices=[('C2', 'В совершенстве'), ('C1', 'Очень хорошо'), ('B2', 'Хорошо'), ('B1', 'Разговорный'), ('A2', 'Обучаюсь'), ('A1', 'Начальный'), ('0', 'Не знаю')], default='', max_length=150, verbose_name='Знание русского языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='turkish',
            field=models.CharField(blank=True, choices=[('C2', 'В совершенстве'), ('C1', 'Очень хорошо'), ('B2', 'Хорошо'), ('B1', 'Разговорный'), ('A2', 'Обучаюсь'), ('A1', 'Начальный'), ('0', 'Не знаю')], default='', max_length=150, verbose_name='Знание турецкого языка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
