# Generated by Django 3.2 on 2023-08-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vacancy_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='employercompany',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='employercompany_avatar/'),
        ),
    ]
