# Generated by Django 3.2 on 2023-08-30 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employercompany_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employercompany',
            name='avatar',
        ),
    ]
