# Generated by Django 3.2 on 2023-09-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230905_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='country',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='страна'),
        ),
    ]
