# Generated by Django 3.2 on 2023-09-05 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vacancy_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employercompany',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='country',
        ),
        migrations.AddField(
            model_name='employercompany',
            name='country',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='страна'),
        ),
    ]
