# Generated by Django 3.2 on 2023-09-11 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230906_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewvacancy',
            name='vacancy_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy', verbose_name='Вакансия'),
        ),
    ]
