# Generated by Django 3.2 on 2023-09-11 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20230911_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewvacancy',
            name='applicant_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль соискателя'),
        ),
        migrations.AlterField(
            model_name='reviewvacancy',
            name='status',
            field=models.CharField(choices=[('Одобрено', 'Одобрено'), ('На рассмотрении', 'На рассмотрении'), ('Отказано', 'Отказано')], default='Under_consideration', max_length=20, verbose_name='Статус отклика'),
        ),
    ]
