# Generated by Django 3.2 on 2023-09-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_vacancy_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='exchange',
            field=models.CharField(blank=True, choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('KGS', 'KGS'), ('KZT', 'KZT')], default='', max_length=10),
        ),
    ]
