# Generated by Django 3.2 on 2023-09-11 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_auto_20230911_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewvacancy',
            name='rejection_message',
        ),
        migrations.AlterField(
            model_name='reviewvacancy',
            name='applicant_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Профиль соискателя'),
        ),
        migrations.AlterField(
            model_name='reviewvacancy',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работодатель'),
        ),
        migrations.AlterField(
            model_name='reviewvacancy',
            name='status',
            field=models.CharField(blank=True, choices=[('Одобрено', 'Одобрено'), ('На рассмотрении', 'На рассмотрении'), ('Отказано', 'Отказано')], default='На рассмотрении', max_length=20, verbose_name='Статус отклика'),
        ),
    ]
