# Generated by Django 3.2 on 2023-09-20 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230912_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
