# Generated by Django 3.2 on 2023-09-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230924_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='student',
            new_name='user',
        ),
    ]
