# Generated by Django 3.2 on 2023-09-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_student_invitation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='amount_in_text',
            field=models.CharField(default='тридцать пять тысяч', max_length=128, null=True, verbose_name='Сумма буквами'),
        ),
    ]
