# Generated by Django 3.2 on 2023-09-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_tariff_amount_in_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='amount_in_text',
            field=models.CharField(default='десять тысяч', max_length=128, null=True, verbose_name='Сумма буквами'),
        ),
    ]
