# Generated by Django 3.2 on 2023-09-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_tariff_amount_in_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='amount_choice',
            field=models.IntegerField(choices=[(10000, 'Десять тысяч'), (20000, 'Двадцать тысяч'), (35000, 'Тридцать пять тысяч')], default=10000, verbose_name='Вариант тарифа'),
        ),
    ]
