# Generated by Django 3.2 on 2023-11-13 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20231113_1331'),
        ('core', '0022_alter_vacancy_salary'),
    ]

    operations = [
    ]
