# Generated by Django 3.2 on 2023-09-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_tariff_amount_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='exchange',
            field=models.CharField(blank=True, choices=[('RUB', 'RUB'), ('USD', 'USD'), ('EUR', 'EUR'), ('KGS', 'KGS'), ('KZT', 'KZT')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
