# Generated by Django 3.2 on 2023-11-28 07:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20231113_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyreview',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='contractadmin',
            name='given_by',
            field=ckeditor.fields.RichTextField(verbose_name='Выдан (УГНС по Ленинскому району)'),
        ),
        migrations.AlterField(
            model_name='employercompany',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='improvementidea',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст идеи'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reviewvacancy',
            name='employer_comment',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Комментарий работодателя'),
        ),
        migrations.AlterField(
            model_name='university',
            name='address',
            field=ckeditor.fields.RichTextField(verbose_name='Адрес на немецком'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contact_info',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='destination_point',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Пункт назначения'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='duty',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Обязанности работника'),
        ),
    ]
