# Generated by Django 3.2 on 2023-10-13 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_companyreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'Принлашение на вакансию', 'verbose_name_plural': 'ОПриглашения на вакансии'},
        ),
    ]
