# Generated by Django 3.2 on 2023-11-09 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0026_auto_20231025_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
            ],
        ),
        migrations.AlterModelOptions(
            name='contractadmin',
            options={'ordering': ['id'], 'verbose_name': 'Администратор для контрактов', 'verbose_name_plural': 'Администраторы для контрактов'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'Приглашение на вакансию', 'verbose_name_plural': 'Приглашения на вакансии'},
        ),
        migrations.AlterModelOptions(
            name='profilecounter',
            options={'verbose_name': 'Количество зарегистрированных пользователей', 'verbose_name_plural': 'Количество зарегистрированных пользователей'},
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.employercompany', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='companyreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employercompany', verbose_name='Работодатель'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('declined', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vacancy', verbose_name='Вакансия'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Подкатегория')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category', verbose_name='Категория')),
            ],
        ),
        migrations.AddField(
            model_name='vacancy',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subcategory', verbose_name='Подкатегория'),
        ),
    ]
