# Generated by Django 3.2 on 2023-12-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Календарь', 'verbose_name_plural': 'Календарь'},
        ),
    ]
