# Generated by Django 3.2 on 2023-11-28 08:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_vacancy_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employercompany',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='contact_info',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Контактные данные'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='destination_point',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Пункт назначения'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='duty',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Обязанности работника'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='extra_info',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=255, verbose_name='Доп. информация'),
        ),
    ]
