# Generated by Django 3.2 on 2023-11-29 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20231129_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'Контактный данные', 'verbose_name_plural': 'Контактные данные'},
        ),
        migrations.AddField(
            model_name='sociallink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
