# Generated by Django 3.2 on 2023-11-29 09:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0006_auto_20231129_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст для футера'),
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logos/', verbose_name='Изображение логотипа')),
                ('description', models.TextField(blank=True, verbose_name='Описание логотипа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('external_url', models.URLField(blank=True, verbose_name='Внешний URL логотипа')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создано пользователем')),
            ],
        ),
    ]
